---
- hosts: Ed_AnsibleHost2_Prod_SWARMMaster
  become: true
  become_user: root
  tasks:
  - name: Install httpd server 
    yum: name=httpd state=present
  - name: Start the httpd server
    service: name=httpd state=started
  - name: Deploy Sonal's html file
    copy: src=index.html dest=/var/www/html
    notify: Restart the httpd server
  handlers:
  - name: Restart the httpd server
    service: name=httpd state=restarted
